### ISSUE TITLE
Lage service for JSONPatch objekter

### ISSUE THREAD

**Issue by MrFranzen** [Informasjonsforvaltning/catalog-history-service#3]
## 🚀 Feature forespørsel
Lage service for JSONPatch objekter

### Feature beskrivelse
Lag en service for håndtering av objekter i mongodb, gjør disse om til json patch objekter slik at det kan håndteres av denne packagen. 

### Hvorfor trenger vi det?
For å benytte seg av package til json patch og godt design for håndtering og oppdatering av json objekter. Skal benyttes for endringsloggen.

### Sjekkliste (Sjekk av etter issue er laget)

- [ ] Lagt til label(s)
- [ ] Lagt i utviklingsbrettet (Project)

**Comment by NilsOveTen** [comment]
Usikker på om dette i det hele tatt skal gjøres. Men om vi trenger at den produserer diff for en spesifikk oppdatering har vi et problem i pakkene som er tilgjengelige for json-patch i GO, tipper vi i så fall bør refaktorere til noe som har bedre støtte for json-patch eventuelt sette opp et hjelpe-api for å produsere diff'en.

**Comment by pooriamehregan** [comment]
@NilsOveTen Er denne saken fortsatt relevant? Eller kan det lukkes og fjernes fra blocked?

**Comment by NilsOveTen** [comment]
eh, vi lukker. Kan eventuelt lage et nytt issue om vi ser et behov senere

**Comment by NilsOveTen** [comment]
wont fix
