### ISSUE TITLE
Rettigheter for lesebrukere, opprettelse

### ISSUE THREAD

**Issue by MrFranzen** [Informasjonsforvaltning/catalog-history-service#4]
## 🚀 Feature forespørsel
Opprette lesebruker for visning av endringslogg

### Feature beskrivelse
Det er bare ønskelig at en lesebruker skal ha tilgang til visning av en forenkler endringslogg, denne må opprettes.

### Hvorfor trenger vi det?
For å gjøre fremvisning av begrep og loggen enklere enn om man viste frem alle felter i dagen endringsløsning

### Sjekkliste (Sjekk av etter issue er laget)

- [ ] Lagt til label(s)
- [ ] Lagt i utviklingsbrettet (Project)

**Comment by NilsOveTen** [comment]
Løst av https://github.com/Informasjonsforvaltning/catalog-history-service/commit/59f6ddad00c97df1f481534a99c2268d74e51f0a
